In [6]:
#determine the dimension of array and creating 2d array
import numpy as np
a = np.array([(1,2,3,4,5),(1,2,3,4,5)])
print(a.ndim) #dimension
print(a.itemsize) #byte size
print(a.dtype) #data type
print(a.size) #size
print(a.shape) #shape

2
4
int32
10
(2, 5)


In [9]:
#reshaping
import numpy as np
a=np.array([(1,2,3,4,5),(6,7,8,9,1)])
print(a)
a =a.reshape(5,2)
print(a)

[[1 2 3 4 5]
 [6 7 8 9 1]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]]


In [28]:
#slicing
import numpy as np
a=np.array([(1,2,3,4,5),(6,7,8,9,1)])
print(a[0,2])
print(a[0:,3])
print(a[0:2,3])
print(a[1][2])
#linespacing 
b=np.linspace(1,3,5)
print(b)

3
[4 9]
[4 9]
8
[1.  1.5 2.  2.5 3. ]


In [36]:
import numpy as np
a=np.array([(1,2,3,4,5),(6,7,8,9,1)])
#maximum
print(a.max())
#minimum
print(a.min())
#sum
print(a.sum())
#sum of column
print(a.sum(axis=0))
#sum of row
print(a.sum(axis=1))
#squareroot
print(np.sqrt(a))
#standard deviation
print(np.std(a))

9
1
46
[ 7  9 11 13  6]
[15 31]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         1.        ]]
2.727636339397171


In [44]:
import numpy as np
a=np.array([(1,2,3,4,5),(6,7,8,9,1)])
b=np.array([(1,2,3,4,5),(6,7,8,9,1)])
#matrix summation
print(a+b)
#matrix subtraction
print(a-b)
#matrix multiplication
print(a*b)
#matrix division
print(a/b)
#concadination
#1verticalstacking
print(np.vstack((a,b)))
#horizontalstacking
print(np.hstack((a,b)))
#converting 2d array to 1d
print(a.ravel())

[[ 2  4  6  8 10]
 [12 14 16 18  2]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ 1  4  9 16 25]
 [36 49 64 81  1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 2 3 4 5]
 [6 7 8 9 1]
 [1 2 3 4 5]
 [6 7 8 9 1]]
[[1 2 3 4 5 1 2 3 4 5]
 [6 7 8 9 1 6 7 8 9 1]]
[1 2 3 4 5 6 7 8 9 1]
